Blog/urls.py
# flake8: noqa
from django.urls import path, include
from rest_framework import routers
from .views import (
    SubscriberApiView,
    BlogApiView,
    HomeView,
    ArticlesView,
    subscribeView,
    AboutView,
    DetailArticleView,
    CreateArticleView,
    UpdateArticleView,
    DeleteArticleView,
    user_login,
    user_logout,
)
from django.contrib.auth import views as auth_views

router = routers.DefaultRouter()
router.register('subscriber', SubscriberApiView)
router.register('blog', BlogApiView)

app_name = 'Blog'

urlpatterns = [
    path("api/", include(router.urls)),
    path('', HomeView.as_view(), name="Home"),
    path('subscribe', subscribeView, name="Subscribe"),
    path('who', AboutView.as_view(), name='Who'),
    path('articles', ArticlesView.as_view(), name="Articles"),
    path('article/<slug>/', DetailArticleView.as_view(), name="Article_Detail"),
    path('new', CreateArticleView.as_view(), name="new_Article"),
    path('article/<slug>/edit/', UpdateArticleView.as_view(), name="update_Article"),
    path('article/<slug>/delete/', DeleteArticleView.as_view(), name="delete_Article"),
    path('IamGitau/admin/login', user_login, name='login'),
    path('IamGitau/admin/logout', user_logout, name='logout'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('IamGitau/admin/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('IamGitau/admin/password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('IamGitau/admin/password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('IamGitau/admin/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('IamGitau/admin/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('IamGitau/admin/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_done'),
]

myBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('Blog.urls')),
    path('api-auth', include('rest_framework.urls')),

]

Blog/models.py
# flake8: noqa
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .utils import readTime


class Blog(models.Model):
    """
    Blog model
    """
    py = 'Python'
    topics = [
        (py, "Python"),
        ("javascript", "javascript  "),
        ("vue js", "vue js"),
        ("Express js", "Express js"),
        ("Laravel", "Laravel"),
        ("Flutter", "Flutter"),
        ("Django", "Django"),
        ("Es6", "Es6"),
        ("IDEs", "IDEs"),
        ("node js", "node js"),
    ]
    noLabel = 'noLabel'
    labels = [
        (noLabel, 'noLabel'),
        ("100DaysOfCode", "100DaysOfCode"),
        ("CodeChallenges", "CodeChallenges"),
    ]
    Title = models.CharField(max_length=2000, null=False, blank=False, help_text='Article title is required',
                             unique=True)
    Author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=1)
    Body = models.TextField(blank=False, null=False, help_text='Input blog body')
    slug = models.SlugField(max_length=200, null=False, blank=False, help_text='Article slug is required', unique=True)
    created_at = models.DateTimeField(_('created at'), default=timezone.now)
    tag = models.CharField(max_length=200, blank=False, null=False, choices=topics, default=py)
    label = models.CharField(max_length=200, blank=False, null=False, choices=labels, default=noLabel)

    def __str__(self):
        return self.Title

    def latest(self):
        return self.created_at >= timezone.now() - datetime.timedelta(days=.5)

    def get_absolute_url(self):
        return reverse('Blog:Article_Detail', kwargs={'slug': self.slug})

    def read(self):
        return readTime(self.Body)

    class Meta:
        verbose_name = _('Blog')
        verbose_name_plural = _("Blog's")


class Subscribers(models.Model):
    """
    Subscribers model
    """
    Email = models.EmailField(max_length=200, null=False, blank=False, unique=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.Email

    def clean(self):
        super().clean()
        self.Email = self.normalize_email(self.Email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        from django.core.mail import send_mail
        send_mail(subject, message, from_email, [self.Email], **kwargs)

    @classmethod
    def normalize_email(cls, Email):
        """
        Normalize the email address by lower casing the domain part of it.
        """
        email = Email or ''
        try:
            email_name, domain_part = email.strip().rsplit('@', 1)
        except ValueError:
            pass
        else:
            email = email_name + '@' + domain_part.lower()
        return email

    class Meta:
        verbose_name = _('Subscriber')
        verbose_name_plural = _('Subscribers')

Blog/forms.py
from django import forms
from django.contrib.auth.forms import UsernameField, AuthenticationForm
from django.contrib.auth.models import User
from .models import Blog, Subscribers
from pagedown.widgets import AdminPagedownWidget


class ProfileAuthenticationForm(AuthenticationForm):
    username = UsernameField(label='',
                             required=True, max_length=200,
                             widget=forms.TextInput(
                                 attrs={'placeholder': 'Username', 'spellcheck': 'false', 'autofocus': False}))
    password = forms.CharField(
        label='',
        strip=False,
        required=True, max_length=200,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'autocomplete': 'current-password',
                'spellcheck': 'false',
                'type': 'password'}),
    )

    class Meta:
        model = User


class NewBlogForm(forms.ModelForm):
    Title = forms.CharField(
        strip=False,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': "Article Title",
            'type': 'text',
        }))

    slug = forms.CharField(
        strip=False,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': "Article Slug",
            'type': 'text',
        }))

    class Meta:
        model = Blog
        fields = ('Title', 'Author', 'slug', 'tag', 'label', 'created_at', 'Body')


class SubForm(forms.ModelForm):
    Email = forms.CharField(
        label='',
        strip=False,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': "Email",
            'type': 'email',
        }))

    class Meta:
        model = Subscribers
        fields = ['Email']

Blog/views.py
from django.contrib import messages
from django.views.generic import (
    TemplateView,
    DetailView,
    CreateView,
    ListView,
    UpdateView,
    DeleteView
)
from rest_framework import viewsets
from .serializers import SubscriberSerializer, BlogSerializer
from .models import Blog, Subscribers
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import ProfileAuthenticationForm, SubForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


class BlogApiView(viewsets.ModelViewSet):
    """
    BlogApiView Handle blog Api
    """
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer


class SubscriberApiView(viewsets.ModelViewSet):
    """
    SubscriberApiView Handle subscribers Api
    """
    queryset = Subscribers.objects.all()
    serializer_class = SubscriberSerializer


class HomeView(ListView):
    """
    HomeView:: Show index page
    """
    template_name = "Blog/Index.html"
    model = Blog
    # context_object_name = 'articles'
    extra_context = {
        'articles': Blog.objects.order_by('-created_at')[:5],
        '100days': Blog.objects.order_by('-created_at').filter(label__icontains="100DaysOfCode")[:5],
        'challenges': Blog.objects.order_by('-created_at').filter(label__icontains="CodeChallenges")[:5],
    }


class ArticlesView(ListView):
    """
    ArticlesView:: Show all article
    """
    template_name = 'Blog/Articles.html'
    model = Blog
    context_object_name = 'articles'
    ordering = ['-created_at']


def subscribeView(request):
    """
    ConfirmView:: Confirm subscription page
    """
    if request.method == 'POST':
        form = SubForm(request.POST or None)

        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, f"Thanks for subscribing")
            return redirect(to='Blog:Home')

        else:
            messages.add_message(request, messages.ERROR, f"Email is taken.")
            return redirect(to='Blog:Subscribe')

    form = SubForm(request.POST or None)
    context = {
        'form': form,
    }
    return render(request, 'Blog/Subscribe.html', context)


class AboutView(TemplateView):
    """
    AboutView:: About Page
    """
    template_name = 'Blog/About.html'


class DetailArticleView(DetailView):
    model = Blog
    template_name = 'Blog/Detail.html'
    articleRange = [1, 2, 3]
    extra_context = {
        "articleRange": articleRange
    }


class CreateArticleView(LoginRequiredMixin, CreateView):
    from .forms import NewBlogForm
    model = Blog
    form_class = NewBlogForm

    def form_valid(self, form):
        form.instance.Author = self.request.user
        return super().form_valid(form)


class UpdateArticleView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    from .forms import NewBlogForm
    model = Blog
    form_class = NewBlogForm

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.Author = self.request.user
            return super().form_valid(form)

    def test_func(self):
        article = self.get_object()  # current article being edited
        if self.request.user.is_authenticated:
            return True
        return False


class DeleteArticleView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blog
    articleRange = [1, 2, 3]
    extra_context = {
        "articleRange": articleRange
    }
    success_url = '/'

    def test_func(self):
        article = self.get_object()  # current article being edited
        if self.request.user.is_authenticated:
            return True
        return False


def user_login(request):
    """
    :param request:
    :return:
    """
    if request.method == 'POST':
        print("Mull")
        form = ProfileAuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print(username)
            print(password)
            current_user_login = authenticate(username=username, password=password)

            if current_user_login is not None:
                login(request, current_user_login)
                return redirect(to='Blog:Who')
            else:
                return redirect(to='Blog:login')

    form = ProfileAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'Blog/login.html', context)


@login_required
def user_logout(request):
    """
    :param request:
    :return:
    """
    logout(request)
    return redirect(to="Blog:Home")

templates/Blog/Include/ArticleError.html
<div style="padding: 40px; background-color: #eeeeee; border-radius: 5px; margin: 5px 0">
    <p style="
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        font-size: 1.2em;
        color:#2a2a2a;
    "> 
        No Posts Posted of late 
    </p>
</div>

templates/Blog/Include/ArticlePhoto.html
{% load static %}

{% if article.tag == 'javascript' or  article.tag == 'Es6' %}
    <img class="js" src="{% static 'Images/js2.png' %}" alt="Js icon">
{% elif article.tag == 'vue js' %}
    <img class="vue" src="{% static 'Images/vue.png' %}" alt="Js icon">
{% elif article.tag == 'Python' %}
    <img class="py" src="{% static 'Images/python.jpg' %}" alt="python icon">
{% elif article.tag == 'Express js' %}
    <img class="ex" src="{% static 'Images/expressjslogo.png' %}" alt="Js icon">
{% elif article.tag == 'node js' %}
    <img class="nodejs" src="{% static 'Images/nodejs.svg' %}" alt="node js icon">
{% elif article.tag == 'Flutter' %}
    <img class="flutter" src="{% static 'Images/flutter2.png' %}" alt="Flutter icon">
{% elif article.tag == 'Laravel' %}
    <img class="lara" src="{% static 'Images/Laravel.png' %}" alt="Laravel icon">
{% elif article.tag == 'Django' %}
    <img class="dj" src="{% static 'Images/dj.png' %}" alt="Django icon">
{% elif article.tag == 'goland' %}
    <img class="ides-s" src="{% static 'Images/flutter2.png' %}" alt="goland logo">
{% elif article.tag == 'webstorm' %}
    <img class="ides-s" src="{% static 'Images/flutter2.png' %}" alt="webstorm logo">
{% elif article.tag == 'phpstorm' %}
    <img class="ides-s" src="{% static 'Images/Laravel.png' %}" alt="phpstorm logo">
{% elif article.tag == 'pycharm' %}
    <img class="ides-s" src="{% static 'Images/dj.png' %}" alt="pycharm logo">
{% else %}
{% endif %}

templates/Blog/Include/Footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/Footer.css' %}">

<footer>
    <div class="footer">
        <ul>
            <li><a href="{% url 'Blog:Who' %}">About me</a></li>
            <li><a href="{% url 'Blog:Subscribe' %}">Subscribe</a></li>
            <li><a target="_blank" href="https://ko-fi.com/josephGitau">Ko-Fi</a></li>
            <li><a target="_blank" href="https://patreon.com/IamGitau">Patreon</a></li>
        </ul>
    </div>
</footer>

templates/Blog/Include/Header.html
<header id="Dheader">

    <div class="header">

        <div class="logo">
            <a href="{% url 'Blog:Home' %}">IamGitau</a>
        </div>

        <div class="cn-rt">
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'Blog:Articles' %}">articles</a></li>

                    {% if user.is_authenticated %}

                        <li><a href="{% url 'Blog:Who' %}">{{ user.username }}</a></li>
                        <li><a href="{% url 'Blog:new_Article' %}">new</a></li>

                    {% else %}
                        <li><a href="{% url 'Blog:Who' %}">who?</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</header>

templates/Blog/Include/SingleArticle.html
{% load static %}
<a class="articleLink" href="{% url 'Blog:Article_Detail' article.slug %}">
    <div class="sn-art">
        <div class="sn-img">
            {% include 'Blog/Include/ArticlePhoto.html' %}
        </div>
        <div class="sn-art-tl">
            <p class="art-title">{{ article.Title }}</p>
            {% if article.read < '1' %}
                <p class="read_time">less than 1 minutes</p>
            {% elif article.read >= '1' %}
                <p class="read_time">{{ article.read }} minutes</p>
            {% elif article.read >= '10' %}
                <p class="read_time">10 minutes</p>
            {% else %}
                <p></p>
            {% endif %}
        </div>
        {% if article.latest %}
            <p class="ar-label">! New !</p>
        {% else %}
        {% endif %}
    </div>
</a>