Blog/urls.py
# flake8: noqa
from django.urls import path, include
from rest_framework import routers
from .views import (
    SubscriberApiView,
    BlogApiView,
    HomeView,
    ArticlesView,
    subscribeView,
    AboutView,
    DetailArticleView,
    CreateArticleView,
    UpdateArticleView,
    DeleteArticleView,
    user_login,
    user_logout,
)
from django.contrib.auth import views as auth_views

router = routers.DefaultRouter()
router.register('subscriber', SubscriberApiView)
router.register('blog', BlogApiView)

app_name = 'Blog'

urlpatterns = [
    path("api/", include(router.urls)),
    path('', HomeView.as_view(), name="Home"),
    path('subscribe', subscribeView, name="Subscribe"),
    path('who', AboutView.as_view(), name='Who'),
    path('articles', ArticlesView.as_view(), name="Articles"),
    path('article/<slug>/', DetailArticleView.as_view(), name="Article_Detail"),
    path('new', CreateArticleView.as_view(), name="new_Article"),
    path('article/<slug>/edit/', UpdateArticleView.as_view(), name="update_Article"),
    path('article/<slug>/delete/', DeleteArticleView.as_view(), name="delete_Article"),
    path('IamGitau/admin/login', user_login, name='login'),
    path('IamGitau/admin/logout', user_logout, name='logout'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('IamGitau/admin/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('IamGitau/admin/password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('IamGitau/admin/password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('IamGitau/admin/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('IamGitau/admin/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('IamGitau/admin/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_done'),
]

myBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('Blog.urls')),
    path('api-auth', include('rest_framework.urls')),

]

Blog/models.py
# flake8: noqa
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .utils import readTime


class Blog(models.Model):
    """
    Blog model
    """
    py = 'Python'
    topics = [
        (py, "Python"),
        ("javascript", "javascript  "),
        ("vue js", "vue js"),
        ("Express js", "Express js"),
        ("Laravel", "Laravel"),
        ("Flutter", "Flutter"),
        ("Django", "Django"),
        ("Es6", "Es6"),
        ("IDEs", "IDEs"),
        ("node js", "node js"),
    ]
    noLabel = 'noLabel'
    labels = [
        (noLabel, 'noLabel'),
        ("100DaysOfCode", "100DaysOfCode"),
        ("CodeChallenges", "CodeChallenges"),
    ]
    Title = models.CharField(max_length=2000, null=False, blank=False, help_text='Article title is required',
                             unique=True)
    Author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=1)
    Body = models.TextField(blank=False, null=False, help_text='Input blog body')
    slug = models.SlugField(max_length=200, null=False, blank=False, help_text='Article slug is required', unique=True)
    created_at = models.DateTimeField(_('created at'), default=timezone.now)
    tag = models.CharField(max_length=200, blank=False, null=False, choices=topics, default=py)
    label = models.CharField(max_length=200, blank=False, null=False, choices=labels, default=noLabel)

    def __str__(self):
        return self.Title

    def latest(self):
        return self.created_at >= timezone.now() - datetime.timedelta(days=.5)

    def get_absolute_url(self):
        return reverse('Blog:Article_Detail', kwargs={'slug': self.slug})

    def read(self):
        return readTime(self.Body)

    class Meta:
        verbose_name = _('Blog')
        verbose_name_plural = _("Blog's")


class Subscribers(models.Model):
    """
    Subscribers model
    """
    Email = models.EmailField(max_length=200, null=False, blank=False, unique=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.Email

    def clean(self):
        super().clean()
        self.Email = self.normalize_email(self.Email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        from django.core.mail import send_mail
        send_mail(subject, message, from_email, [self.Email], **kwargs)

    @classmethod
    def normalize_email(cls, Email):
        """
        Normalize the email address by lower casing the domain part of it.
        """
        email = Email or ''
        try:
            email_name, domain_part = email.strip().rsplit('@', 1)
        except ValueError:
            pass
        else:
            email = email_name + '@' + domain_part.lower()
        return email

    class Meta:
        verbose_name = _('Subscriber')
        verbose_name_plural = _('Subscribers')

Blog/forms.py
from django import forms
from django.contrib.auth.forms import UsernameField, AuthenticationForm
from django.contrib.auth.models import User
from .models import Blog, Subscribers
from pagedown.widgets import AdminPagedownWidget


class ProfileAuthenticationForm(AuthenticationForm):
    username = UsernameField(label='',
                             required=True, max_length=200,
                             widget=forms.TextInput(
                                 attrs={'placeholder': 'Username', 'spellcheck': 'false', 'autofocus': False}))
    password = forms.CharField(
        label='',
        strip=False,
        required=True, max_length=200,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'autocomplete': 'current-password',
                'spellcheck': 'false',
                'type': 'password'}),
    )

    class Meta:
        model = User


class NewBlogForm(forms.ModelForm):
    Title = forms.CharField(
        strip=False,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': "Article Title",
            'type': 'text',
        }))

    slug = forms.CharField(
        strip=False,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': "Article Slug",
            'type': 'text',
        }))

    class Meta:
        model = Blog
        fields = ('Title', 'Author', 'slug', 'tag', 'label', 'created_at', 'Body')


class SubForm(forms.ModelForm):
    Email = forms.CharField(
        label='',
        strip=False,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': "Email",
            'type': 'email',
        }))

    class Meta:
        model = Subscribers
        fields = ['Email']

Blog/views.py
from django.contrib import messages
from django.views.generic import (
    TemplateView,
    DetailView,
    CreateView,
    ListView,
    UpdateView,
    DeleteView
)
from rest_framework import viewsets
from .serializers import SubscriberSerializer, BlogSerializer
from .models import Blog, Subscribers
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import ProfileAuthenticationForm, SubForm
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


class BlogApiView(viewsets.ModelViewSet):
    """
    BlogApiView Handle blog Api
    """
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer


class SubscriberApiView(viewsets.ModelViewSet):
    """
    SubscriberApiView Handle subscribers Api
    """
    queryset = Subscribers.objects.all()
    serializer_class = SubscriberSerializer


class HomeView(ListView):
    """
    HomeView:: Show index page
    """
    template_name = "Blog/Index.html"
    model = Blog
    # context_object_name = 'articles'
    extra_context = {
        'articles': Blog.objects.order_by('-created_at')[:5],
        '100days': Blog.objects.order_by('-created_at').filter(label__icontains="100DaysOfCode")[:5],
        'challenges': Blog.objects.order_by('-created_at').filter(label__icontains="CodeChallenges")[:5],
    }


class ArticlesView(ListView):
    """
    ArticlesView:: Show all article
    """
    template_name = 'Blog/Articles.html'
    model = Blog
    context_object_name = 'articles'
    ordering = ['-created_at']


def subscribeView(request):
    """
    ConfirmView:: Confirm subscription page
    """
    if request.method == 'POST':
        form = SubForm(request.POST or None)

        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, f"Thanks for subscribing")
            return redirect(to='Blog:Home')

        else:
            messages.add_message(request, messages.ERROR, f"Email is taken.")
            return redirect(to='Blog:Subscribe')

    form = SubForm(request.POST or None)
    context = {
        'form': form,
    }
    return render(request, 'Blog/Subscribe.html', context)


class AboutView(TemplateView):
    """
    AboutView:: About Page
    """
    template_name = 'Blog/About.html'


class DetailArticleView(DetailView):
    model = Blog
    template_name = 'Blog/Detail.html'
    articleRange = [1, 2, 3]
    extra_context = {
        "articleRange": articleRange
    }


class CreateArticleView(LoginRequiredMixin, CreateView):
    from .forms import NewBlogForm
    model = Blog
    form_class = NewBlogForm

    def form_valid(self, form):
        form.instance.Author = self.request.user
        return super().form_valid(form)


class UpdateArticleView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    from .forms import NewBlogForm
    model = Blog
    form_class = NewBlogForm

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.Author = self.request.user
            return super().form_valid(form)

    def test_func(self):
        article = self.get_object()  # current article being edited
        if self.request.user.is_authenticated:
            return True
        return False


class DeleteArticleView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blog
    articleRange = [1, 2, 3]
    extra_context = {
        "articleRange": articleRange
    }
    success_url = '/'

    def test_func(self):
        article = self.get_object()  # current article being edited
        if self.request.user.is_authenticated:
            return True
        return False


def user_login(request):
    """
    :param request:
    :return:
    """
    if request.method == 'POST':
        print("Mull")
        form = ProfileAuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print(username)
            print(password)
            current_user_login = authenticate(username=username, password=password)

            if current_user_login is not None:
                login(request, current_user_login)
                return redirect(to='Blog:Who')
            else:
                return redirect(to='Blog:login')

    form = ProfileAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'Blog/login.html', context)


@login_required
def user_logout(request):
    """
    :param request:
    :return:
    """
    logout(request)
    return redirect(to="Blog:Home")

templates/Blog/About.html
{% extends 'Blog/App.html' %}

{% block Header %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/About.css' %}">
{% endblock %}

{% block Content %}
    <div class="content">
        <h1>Who am I?</h1>
        <div class="proContent">
            <p>
                I’m Joseph Gitau, a full stack software developer. I like to write about things that I have learned and
                problems that I face.
                I am also a machine learning and Deep learning enthusiast. I love playing games out of work : Call of
                Duty, Fortnite, and my favorite Eve online.
            </p>
            <div class="ides">
                <h2>Editors</h2>
                <ul>
                    <li><a target="_blank" title="Pycharm" href="https://www.jetbrains.com/pycharm/">Pycharm</a></li>
                    <li><a target="_blank" title="Phpstorm" href="https://www.jetbrains.com/phpstorm/">PhpStorm</a></li>
                    <li><a target="_blank" title="Android Studio" href="https://developer.android.com/studio">Android
                        Studio</a></li>
                </ul>
            </div>
            <div class="ides">
                <h2>Email</h2>
                <ul>
                    <li><a  title="qwartypa@gmail.com">qwartypa@gmail.com</a></li>
                </ul>
            </div>
            <div class="ides">
                <h2>BTC</h2>
                <ul>
                    <li>3BL2Lrq5xzeyiwxnS62s6znPQdSxDThDFh</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/Blog/App.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'Images/me.jpg' %}" type="image/x-icon"sizes="32x32">
    <link rel="stylesheet" href="{% static 'css/Styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/Header.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Gotu&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/c631255f04.js" crossorigin="anonymous"></script>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'css/material.css' %}">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    {% block Header %}{% endblock %}
    <title>IamGitau | Full Stack Developer Articles</title>
</head>
<body class='typora-export os-windows'>
{% include 'Blog/Include/Header.html' %}
<main>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <script>M.toast({html: "{{message}}", classes: 'green', displayLength: 2000});</script>
            {% elif message.tags == 'info' %}
                <script>M.toast({html: "{{message}}", classes: 'blue', displayLength: 2000});</script>
            {% elif message.tags == 'warning' %}
                <script>M.toast({html: "{{message}}", classes: 'orange', displayLength: 2000});</script>
            {% elif message.tags == 'error' %}
                <script>M.toast({html: "{{message}}", classes: 'red', displayLength: 3000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% block Content %}{% endblock %}
</main>
{% include 'Blog/Include/Footer.html' %}
<script src="{% static 'js/scroll.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.8.2/marked.min.js"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/Blog/Articles.html
{% extends 'Blog/App.html' %}
{% block Header %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Articles.css' %}">
    <link rel="stylesheet" href="{% static 'css/Index.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block Content %}
    <div class="content">
        <div class="arc-form">
            <div class="arc-f-fm">
                <div class="search-icon">
                    <i id="SearchIcon" class="fas fa-search fa-lg"></i>
                </div>
                <div class="search-bar">
                    <form>
                        <label>
                            <input type="text" id="SearchBar" onkeyup="SearchArticles()" placeholder="Search Article">
                        </label>
                    </form>
                </div>
            </div>
            <div class="arc-fl-fm" id="filter">
                <h2>Articles</h2>
                <div class="arc-filters">
                    <button type="button">Vue js</button>
                    <button type="button">Express js</button>
                    <button type="button">node js</button>
                    <button type="button">Flutter</button>
                </div>
                <div class="arc-filters colored">
                    <button type="button">Python</button>
                    <button type="button">Django</button>
                    <button type="button">Laravel</button>
                    <button type="button">Es6</button>
                </div>
                <div class="arc-filters">
                    <button type="button">IDEs</button>
                    <button type="button">CodeChallenges</button>
                    <button type="button">#100DaysOfCode</button>
                </div>
            </div>
        </div>
        <div class="cly-arc" id="allArticles">
            <div class="lts-msp-art" id="lts">
                {% for article in articles %}
                    {% include 'Blog/Include/SingleArticle.html' %}
                {% empty %}
                    {% include 'Blog/Include/ArticleError.html' %}
                {% endfor %}
                <div id="noArticles"
                     style="display: none;padding: 40px; background-color: #eeeeee; border-radius: 5px; margin: 5px 0">
                    <p style="display: flex;
                            flex-direction: column;
                            justify-content: center;
                            align-items: center;
                            font-size: 1.2em;
                            color:#2a2a2a;"> Sorry Such Articles Posted </p>
                </div>
            </div>
        </div>
        <div class="education-M">
            <h3>Learn coding for free.</h3>
            <div class="edu-c">
                <ul>
                    <li title="Jetbrains Academy"><a target="_blank" href="https://www.jetbrains.com/academy">Jetbrains
                        Academy </a></li>
                    <li title="Solo Learn"><a target="_blank" href="https://www.sololearn.com">Solo Learn </a></li>
                    <li title="W3schools"><a target="_blank" href="https://w3schools.com">W3schools </a></li>
                    <li title="IamGitau"><a href="https://iamgitau.herokuapp.com">IamGitau </a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        function SearchArticles() {
            let SearchBar, filter, allArticles, articleLink, titleArticle, i, txtValue;

            SearchBar = document.getElementById("SearchBar");
            filter = SearchBar.value.toUpperCase();
            allArticles = document.getElementById("allArticles");
            articleLink = allArticles.getElementsByClassName("articleLink");

            for (i = 0; i < articleLink.length; i++) {
                titleArticle = articleLink[i].getElementsByTagName("p")[0];
                txtValue = titleArticle.textContent || titleArticle.innerText;

                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    articleLink[i].style.display = "";
                } else {
                    articleLink[i].style.display = "none";
                }
            }
        }

        $(document).ready(() => {
            function filterArticles() {

                let art, single, lts, articleLinkF;
                art = document.getElementById('filter');
                single = art.getElementsByTagName('button');
                lts = document.getElementById('lts');
                articleLinkF = lts.getElementsByClassName('articleLink');

                function fil(cargo) {
                    for (let i = 0; i < articleLinkF.length; i++) {
                        if (articleLinkF[i].querySelector(cargo)) {
                            articleLinkF[i].style.display = ''
                        } else {
                            articleLinkF[i].style.display = 'none'
                        }
                    }
                }

                for (let i = 0; i < single.length; i++) {
                    single[i].addEventListener('click', function () {
                        if (single[i].innerHTML === 'Vue js') {
                            fil('.vue')
                        } else if (single[i].innerHTML === 'Python') {
                            fil('.py')
                        } else if (single[i].innerHTML === 'Django') {
                            fil('.dj')
                        } else if (single[i].innerHTML === 'Laravel') {
                            fil('.lara')
                        } else if (single[i].innerHTML === 'Es6' || single[i].innerHTML === 'js') {
                            fil('.js')
                        } else if (single[i].innerHTML === 'Express js') {
                            fil('.ex')
                        } else if (single[i].innerHTML === 'node js') {
                            fil('.nodejs')
                        } else if (single[i].innerHTML === 'Flutter') {
                            fil('.flutter')
                        } else if (single[i].innerHTML === 'IDEs') {
                            fil('.ides-s')
                        } else if (single[i].innerHTML === 'CodeChallenges') {
                            fil('.challenge')
                        } else if (single[i].innerHTML === '#100DaysOfCode') {
                            fil('.DaysOfCode')
                        } else {

                        }
                    })
                }
            }

            filterArticles();
        });
    </script>
    <script src="{% static 'js/search.js' %}"></script>
{% endblock %}

templates/Blog/Index.html
{% extends 'Blog/App.html' %}
{% block Header %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Index.css' %}">
{% endblock %}
{% block Content %}
    <div class="content">
        <div class="my-intro">
            <div class="my-slf">
                <h1>✋ Hey, I'm Joseph Gitau.</h1>
                <p>
                    I'm a full stack software developer. I write about Python,
                    Vue js, Express js, modern JavaScript, Django,Golang, Flutter or Dart and Dotnet Core Framework.
                </p>
                <div class="git-hub">
                    <a target="_blank" href="https://github.com/gitaoh" style='text-decoration:none;'>
                        <div class="git-name">
                            <img src="{% static 'Images/github.svg' %}" alt="github icon">
                            <span>Joseph Gitau</span>
                        </div>
                    </a>
                </div>
            </div>
            <div class="sub-to">
                <div class="email-form">
                    <img 
                        src="{% static 'Images/me.jpg' %}" 
                        alt="photo" 
                        style="width: 130px;height: 80%;border-radius: 50%;filter: brightness(100%);"
                    >
                    <h2>Email Newsletters</h2>
                    <p>Subscribe today to get email updates when a I post a new article.</p>
                    <a class="sub-btn" href="{% url 'Blog:Subscribe' %}">Subscribe</a>
                </div>
            </div>
        </div>
        <div class="cly-arc">
            <div class="lts-arc">
                <div class="lts-msp-tl">
                    <h3>Latest articles</h3>
                    <a class="v-all" href="{% url 'Blog:Articles' %}">View All</a>
                </div>
                <div class="lts-msp-art">
                    {% for article in articles %}
                        {% include 'Blog/Include/SingleArticle.html' %}
                    {% empty %}
                        {% include 'Blog/Include/ArticleError.html' %}
                    {% endfor %}
                </div>
            </div>
            <div class="mst-p-arc">
                <div class="lts-msp-tl" style="margin-top: 30px">
                    <h3>Most popular articles</h3>
                    <a class="v-all" href="{% url 'Blog:Articles' %}">View All</a>
                </div>
                <div class="lts-msp-art">
                    {% for article in articles %}
                        {% include 'Blog/Include/SingleArticle.html' %}
                    {% empty %}
                        {% include 'Blog/Include/ArticleError.html' %}
                    {% endfor %}
                </div>
            </div>
            {% if challenges %}
                {% ifchanged challenges %}
                    <div class="mst-p-arc">
                        <div class="lts-msp-tl" style="margin-top: 30px">
                            <h3>Code Challenges </h3>
                            <a class="v-all" href="{% url 'Blog:Articles' %}">View All</a>
                        </div>
                        <div class="lts-msp-art">
                            {% for article in challenges %}
                                {% include 'Blog/Include/SingleArticle.html' %}
                            {% empty %}
                                {% include 'Blog/Include/ArticleError.html' %}
                            {% endfor %}
                        </div>
                    </div>
                {% endifchanged %}
            {% endif %}
            {% if 100days %}
                {% ifchanged 100days %}
                    <div class="mst-p-arc">
                        <div class="lts-msp-tl" style="margin-top: 30px">
                            <h3>100 Days of code</h3>
                            <a href="{% url 'Blog:Articles' %}">View All</a>
                        </div>
                        <div class="lts-msp-art">
                            {% for article in 100days %}
                                {% include 'Blog/Include/SingleArticle.html' %}
                            {% empty %}
                                {% include 'Blog/Include/ArticleError.html' %}
                            {% endfor %}
                        </div>
                    </div>
                {% endifchanged %}
            {% endif %}
        </div>
        <div class="education-M">
            <h3>Learn coding for free.</h3>
            <div class="edu-c">
                <ul>
                    <li title="Jetbrains Academy"><a target="_blank" href="https://www.jetbrains.com/academy">Jetbrains
                        Academy </a></li>
                    <li title="Solo Learn"><a target="_blank" href="https://www.sololearn.com">Solo Learn </a></li>
                    <li title="W3schools"><a target="_blank" href="https://w3schools.com">W3schools </a></li>
                    <li title="IamGitau"><a href="https://iamgitau.herokuapp.com">IamGitau </a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}{% endblock %}

templates/Blog/Subscribe.html
{% extends 'Blog/App.html' %}

{% block Header %}
    <style>
        .content {
            height: 70vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        #id_Email {
            border: 2px solid #2a2a2a;
            padding: 5px 200px 5px 10px;
            outline: none;
            border-radius: 5px;
            font-size: 1em;
            color: #2a2a2a;
        }

        #id_Email:focus {
            border-width: medium;
        }

        #sub-sub {
            border: thin solid transparent;
            padding: 5px 30px;
            outline: none;
            border-radius: 5px;
            font-size: 1.2em;
            color: #fff;
            background-color: #00da84;
            margin-top: 10px;
            cursor: pointer;
        }

        #sub-sub:hover {
            border-width: 1px;
            border-color: #00da84;
            color: #2a2a2a;
            transition: background-color ease-in-out 200ms;
            background-color: white;
        }

        .errorlist {
            display: flex;
            flex-direction: column;
            align-items: start;
            justify-content: space-evenly;
        }

        .errorlist li {
            list-style: none;
            color: #ff2600;
            font-size: .9em;
        }
    </style>
{% endblock %}

{% block Content %}
    <div class="content">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" id="sub-sub" value="Subscribe">
        </form>
    </div>
{% endblock %}

templates/Blog/blog_form.html
{% extends 'Blog/App.html' %}
{% block Header %}
    {% load static %}
    {% load crispy_forms_filters %}
    <link rel="stylesheet" href="{% static "css/Form.css" %}">
{% endblock %}
{% block Content %}
    <div class="content">
        <form method="post">
            {% csrf_token %}
            <div class="top-Form">
                <h2>Articles Post</h2>
                <button type="submit">Publish</button>
            </div>
            <div class="form">
                {{ form| crispy }}
            </div>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(document).ready(() => {
            $(function () {
                let title = $('#id_Title');
                let body = $('#id_Body');
                $(body).attr('cols', '150');
                $(body).attr('rows', '15');
                $(body).css('max-width', '70vw');
                $(body).css('min-width', '70vw');
                $(body).css('max-height', '50vh');
                $(body).css('min-height', '50vh');
                $('.form-control').css('margin', '30px 0');
                $(".help-block").css('margin', '10px 0');

            });
        })
    </script>
{% endblock %}